# Copyright (c) 2026, solvcon team <contact@solvcon.net>
# BSD 3-Clause License, see COPYING


import json
import os
import pathlib
import subprocess

import pytest


HOOK = (pathlib.Path(__file__).resolve().parent.parent
        / ".claude" / "hooks" / "check-ai-attribution.py")

TRAILER = "Co-authored-by: %s <noreply@%s.com>" % ("Claude", "anthropic")
CREDIT = "%s with %s Code" % ("Generated", "Claude")
ROBOT = "\U0001f916"


def invoke(stdin):
    return subprocess.run([str(HOOK)], input=stdin, capture_output=True,
                          text=True)


def run(command, event="PreToolUse", cwd=None):
    body = {"command": command, "cwd": str(cwd or os.getcwd())}
    if event == "beforeShellExecution":
        payload = dict(body, hook_event_name=event)
    else:
        payload = {"hook_event_name": event, "tool_input": body}
    return invoke(json.dumps(payload))


def blocked(command, **kw):
    out = run(command, **kw)
    return out.returncode == 2 and "Hook violation" in out.stderr


@pytest.mark.parametrize("command", [
    'git commit -m "Fix the solver\n\n%s"' % TRAILER,
    'git commit -m "Fix the solver\n\n%s"' % CREDIT,
    'git commit -am "Fix\n\n%s"' % TRAILER,
    'git commit --message="Fix\n\n%s"' % TRAILER,
    'git commit -m "ok" --trailer "%s"' % TRAILER,
    'git commit -m "x\n\ngenerated WITH Claude"',
    'git commit -m "x\n\nMade with Cursor"',
    'git -C . commit -m "Fix\n\n%s"' % TRAILER,
    'env git commit -m "Fix\n\n%s"' % TRAILER,
    '/usr/bin/git commit -m "Fix\n\n%s"' % TRAILER,
    'git merge --no-ff -m "Merge\n\n%s" topic' % TRAILER,
    'git tag -a v1 -m "Release\n\n%s"' % CREDIT,
    'gh pr create --body "Body\n\n%s"' % CREDIT,
    'gh pr create --title "%s" --body ok' % CREDIT,
    'gh --repo solvcon/modmesh pr create --body "%s"' % CREDIT,
    'gh pr close 1 --comment "%s"' % CREDIT,
    'gh issue comment 1 --body "%s"' % ROBOT,
    'true && git commit -m "x\n\n%s"' % TRAILER,
    'if true; then git commit -m "x\n\n%s"; fi' % TRAILER,
    'gh pr new --body "%s"' % CREDIT,
    'gh --hostname github.com --repo solvcon/modmesh pr create '
    '--body "%s"' % CREDIT,
    'env -u GIT_CONFIG git commit -m "x %s"' % CREDIT,
    'nice -n 19 git commit -m "x %s"' % CREDIT,
    'git commit -m "x\n\nGenerated by AI"',
    'git commit -m "x\n\nWritten with artificial intelligence"',
    'git commit -m "$(cat <<\'EOF\'\nFix\n\n%s\nEOF\n)"' % TRAILER,
    'gh pr create --body "$(cat <<\'EOF\'\nBody\n\n%s\nEOF\n)"' % CREDIT,
    'git commit -F - <<\'EOF\'\nFix\n\n%s\nEOF' % TRAILER,
    'gh pr create --body-file - <<\'EOF\'\nBody\n\n%s\nEOF' % CREDIT,
    'make lint\ngit commit -m "x\n\n%s"' % TRAILER,
])
def test_attribution_is_blocked(command):
    assert blocked(command)


@pytest.mark.parametrize("command", [
    'git commit -m "Fix the solver"',
    'git commit -am "Fix the solver"',
    'git commit --amend --no-edit',
    'git rebase -m main',
    'gh issue create --body "Build files generated with CMake"',
    'gh pr create --title "Regenerate the mesh" --body ok',
    'gh pr view 12',
    'git log --oneline',
    'echo "%s"' % TRAILER,
    'printf "%s" && ls' % CREDIT,
    'git commit -m "Co-authored-by: A Human <human@example.com>"',
    'git commit -m "Co-authored-by: Ada <ada@company.ai>"',
    'git commit -m "Fix the crash created by the cursor drag"',
    'git commit -m "Pick a shape made with the cursor"',
    'git commit -F - <<\'EOF\'\nFix the solver\nEOF',
    "python3 - <<'EOF'\nCASES = ['git commit -m \"%s\"']\nEOF" % CREDIT,
])
def test_clean_commands_pass(command):
    out = run(command)
    assert out.returncode == 0, out.stderr


def test_body_file_is_read(tmp_path):
    (tmp_path / "body.md").write_text("Body text\n\n%s\n" % CREDIT)
    assert blocked("gh pr create --body-file body.md", cwd=tmp_path)
    assert blocked('git commit -F "%s/body.md"' % tmp_path)


def test_clean_body_file_passes(tmp_path):
    (tmp_path / "body.md").write_text("A human wrote this body.\n")
    assert run("gh pr create --body-file body.md",
               cwd=tmp_path).returncode == 0


def test_cursor_gets_a_json_verdict():
    out = run('gh pr create --body "%s"' % CREDIT,
              event="beforeShellExecution")
    assert out.returncode == 0
    verdict = json.loads(out.stdout)
    assert verdict["permission"] == "deny"
    assert "Hook violation" in verdict["user_message"]
    assert "Hook violation" in verdict["agent_message"]


def test_cursor_allows_clean_commands():
    out = run('git commit -m "Fix the solver"',
              event="beforeShellExecution")
    assert out.returncode == 0
    assert out.stdout.strip() == ""


@pytest.mark.parametrize("payload", [
    "not json", "null", "[]", '"text"', '{"tool_input": "x"}',
    '{"tool_input": {"command": 5}}',
])
def test_malformed_input_does_not_crash(payload):
    out = invoke(payload)
    assert out.returncode == 0, out.stderr

# vim: set ff=unix fenc=utf8 et sw=4 ts=4 sts=4 tw=79:
