import os, sys
Import('env')
lpre = 'sc'
sdir = '.'
bdir = '../../tmp/build'
ldir = '.'
libs = list()
# kerpak libraries.
dimlibs = [ 
    'elasticb', # solvcon.kerpak.elastic
]
for ndim in 2, 3:
    for lkey in dimlibs:
        VariantDir('%s/%s%dd' % (bdir, lkey, ndim),
            '%s/%s' % (sdir, lkey), duplicate=0)
    envm = env.Clone()
    envm.Prepend(CCFLAGS=['-DNDIM=%d'%ndim])
    for lkey in dimlibs:
        libs.append(envm.SharedLibrary(
            '%s/%s_%s%dd' % (ldir, lpre, lkey, ndim),
            Glob('%s/%s%dd/*.c' % (bdir, lkey, ndim)),
        ))
# elastic solver needs lapack.
dimlibs = [
    'elastic',  # solvcon.kerpak.elastic
]
for ndim in 2, 3:
    for lkey in dimlibs:
        VariantDir('%s/%s%dd' % (bdir, lkey, ndim),
            '%s/%s' % (sdir, lkey), duplicate=0)
    envm = env.Clone()
    envm.Prepend(CCFLAGS=['-DNDIM=%d'%ndim])
    envm.Prepend(LIBS=['lapack'])
    for lkey in dimlibs:
        libs.append(envm.SharedLibrary(
            '%s/%s_%s%dd' % (ldir, lpre, lkey, ndim),
            Glob('%s/%s%dd/*.c' % (bdir, lkey, ndim)),
        ))
all = Alias(libs)
Default(all)
# vim: set ft=python ff=unix:
