Import('env')
lpre = 'sc'
sdir = '.'
bdir = '../../tmp/build'
ldir = '.'
libs = list()

def make_kplib(lname, lpre, ldir, sdir, bdir, env, extra_links=None):
    """
    Make kerpak libraries.
    """
    libs = []
    for ndim in 2, 3:
        VariantDir('%s/%s%dd' % (bdir, lname, ndim), sdir, duplicate=0)
        envm = env.Clone()
        envm.Prepend(CCFLAGS=['-DNDIM=%d'%ndim])
        if extra_links is not None:
            envm.Prepend(LIBS=extra_links)
        libs.append(envm.SharedLibrary(
            '%s/%s_%s%dd' % (ldir, lpre, lname, ndim),
            Glob('%s/%s%dd/*.c' % (bdir, lname, ndim))))
    return libs
kplibs = [
    ('elastic', ['lapack']), ('elasticb', None),
]
for lname, extra_links in kplibs:
    libs.extend(make_kplib(lname, lpre, ldir, '%s/%s'%(sdir, lname),
        bdir, env, extra_links=extra_links))

all = Alias(libs)
Default(all)
# vim: set ft=python ff=unix:
