import os

env = Environment(ENV=os.environ, LATEXFLAGS='--src-specials',
    TOOLS=[
        'default',
        'paper',
    ],
)

EPSDIR = 'source/_static_generated'
allfigs = list()
for dname in ['latexschematic']:
    pstricks = env.Pstricks(Glob('%s/*.tex'%dname), OUTDIR=EPSDIR)
    allfigs.extend(pstricks)
    allfigs.extend(env.Imconvert(pstricks,
        OUTDIR=EPSDIR, EXT='.png', DPI=300))

env.Default(allfigs)

# vim: set fenc=utf8 ft=python ff=unix ai et nu sw=4 ts=4 tw=79:
