Document: solvcon
Title: Debian solvcon Manual
Author: <insert document author here>
Abstract: This manual describes what solvcon is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/solvcon/solvcon.sgml.gz

Format: postscript
Files: /usr/share/doc/solvcon/solvcon.ps.gz

Format: text
Files: /usr/share/doc/solvcon/solvcon.text.gz

Format: HTML
Index: /usr/share/doc/solvcon/html/index.html
Files: /usr/share/doc/solvcon/html/*.html
