BootStrap: debootstrap
OSVersion: xenial
MirrorURL: http://us.archive.ubuntu.com/ubuntu/


%runscript
    echo "Welcome to SOLVCON singularity instance."

%files
    /tmp/host-username.txt /host-username.txt
    prepare-solvcon-dev.sh /prepare-solvcon-dev.sh

%post
    echo "Prepare to build SOLVCON in singularity instance..."
    sed -i 's/$/ universe/' /etc/apt/sources.list
    apt-get update
    # general tools
    apt-get install vim git -y
    # used for miniconda extraction
    apt-get install bzip2
    # SOLVCON build tools
    apt-get install openssh-client openssh-server liblapack-pic liblapack-dev -y
    apt-get install build-essential unzip -y
    # it currently works in the root path
    echo "Working location: " `pwd`
    # it is /root
    echo $HOME
    apt-get clean

    # I want solvcon source code and folder is managed by the same
    # user who triggers the container execution
    export TARGET_USERNAME=`cat /host-username.txt`
    adduser --no-create-home --disabled-password --gecos "" $TARGET_USERNAME

    # start to build
    export SOLVCON_BUILD_DIR=/opt
    /bin/bash -c "source /prepare-solvcon-dev.sh $SOLVCON_BUILD_DIR"

    # so the normal user could write SOLVCON folder
    chown $TARGET_USERNAME -R $SOLVCON_BUILD_DIR/*
